---
title: "Gov 50 Final Project"
author: "Katherine Rafeiro Jackson"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to payday loans. Indeed, I would like to look at the number of payday loan businessese in a neighbourhood and a neighbourhood's wealth. I would ideally like to be able to create a model, where the number of payday loan businesses in a certain area is a predictor for the median income for that neighbourhood.

This topic is motivated by my walks to work this summer.I would pass by the same 2-3 payday loan businesses everyday and it got me thinking about how low of a median income does a neighbourhood need to have before its residents require payday loans to get by. Expanding this idea further, I could also look into foreign exchange counters, and how they are a predictor of median income, or the immigrant population of an area. 

##Project Proposal

How does the population's confidence in the government in power change as the inflation and unemployment rates change?I believe that the population will have lower confidence in the government if the inflation and unemployment rates are high. However, I also think that the effect of the inflation and unemployment rates on government confidence is small. This makes intuitive sense because inflation and unemployment directly impact the population; thus, individuals "have a reason" to be frustrated towards the government that let the situation get to where it is (high inflation and/or high unemployment). Additionally, I think that other macro factors influence government confidence; inflation and unemployment can't be the only ones, which is why I hypothesize that the effect is small. I hope to merge two datasets to conduct this analysis; the first from FRED, and the second from Pew Research Center. My explanatory variables would be the inflation rate and the unemployment rate over time (measured as a percentage, or rather a decimal number). I would conduct an analysis for each explanatory variable, so these two explanatory variables are independent of one another. My outcome variable is the confidence in the government, which is measured on a scale from 1 to 100. The population's confidence in the government is based on the confidence that a sample (subset of the population) has in the government. The pattern in the data that would provide support to my hypothesis is one where for high inflation and unemployment rates, the population's confidence in the government is low. Relatedly, for low inflation and a low unemployment rate, the population's confidence in the government would be high. Any pattern opposite to the one described in the previous two sentences would disprove my hypothesis. 

